### ISSUE TITLE
Colors slightly different than shadcn

### ISSUE THREAD

**Issue by aviflombaum** [aviflombaum/shadcn-rails#3]
I noticed that the colors are actually slightly different. It seems across all elements, there's a slightly bluer tint to everything. For example, muted text in the original ends up getting #71717A but here it's coming out as #64748B. It's not a huge difference, but it's noticeable. No idea where this got introduced but the settings should be the same as the original default theme.

**Comment by sahilLikes2Code** [comment]
Hey @aviflombaum  I was going through the issue but couldn't recreate it. Both local installation and "http://www.rails-components.com/" use the same text hex code for muted text and I cant seem to find the discrepancy mentioned above. Please check if you could.

<img width="1440" alt="image" src="https://github.com/aviflombaum/shadcn-rails/assets/40363532/1f313b32-0cf2-4051-8f7b-61c03f3c5bfb">
<img width="1440" alt="image" src="https://github.com/aviflombaum/shadcn-rails/assets/40363532/5ecc88f5-30b0-44d5-ae04-2245f9bbde69">

**Comment by aviflombaum** [comment]
Hey @sahilLikes2Code - I meant on the original library site https://ui.shadcn.com - I might have been seeing things but check there.

**Comment by aviflombaum** [comment]
Fixed by #43
