### ISSUE TITLE
Dialog miss a render and can't i use

### ISSUE THREAD

**Issue by sergitejada** [aviflombaum/shadcn-rails#35]
When i install a Dialog, dialog have a `<%= render "components/ui/shared/backdrop", as: "modal" %>` but the generator can import this and cause a error

Solution: try to import the backdrop view when import dialog

**Comment by aviflombaum** [comment]
Thanks - going to fix this now.

**Comment by aviflombaum** [comment]
Closed by [80e7bd3](https://github.com/aviflombaum/shadcn-rails/commit/80e7bd3729b5056474db4e204e1e3338b8e4685e)

**Comment by aviflombaum** [comment]
You can copy the backdrop file by the way out of the source app.

**Comment by aviflombaum** [comment]
https://github.com/aviflombaum/shadcn-rails/blob/main/app/views/components/ui/shared/_backdrop.html.erb
