### ISSUE TITLE
Permit custom direction to dialog

### ISSUE THREAD

**Issue by sergitejada** [aviflombaum/shadcn-rails#36]
Create a custom dialog in diferent postion 
I want use a dialog to a sidebar 
![image](https://github.com/aviflombaum/shadcn-rails/assets/49126831/5f892e38-7b5c-491a-a6e0-24fa1903873b)
I want to use the dialog as a sidebar, and modified the component so that the user can send css to it.
Do you think it would be a good functionality?
![image](https://github.com/aviflombaum/shadcn-rails/assets/49126831/e410797e-7ad5-44be-88a2-2687b55c81d5)
![image](https://github.com/aviflombaum/shadcn-rails/assets/49126831/73e19cc7-dc6d-47a4-891c-cee4e4c1e12b)
![image](https://github.com/aviflombaum/shadcn-rails/assets/49126831/f8da50d2-62af-4ca4-98b8-c10767eec37a)
If you think it would be a good functionality, I can do a PR.
He also thinks we should create a position variable so that we don't have to send css
![Uploading image.png…]()

**Comment by aviflombaum** [comment]
Yes, this would be awesome. I think the original library supports this too. Go for it, I'll review.
