### ISSUE TITLE
Tailwind merge is not used on buttons?

### ISSUE THREAD

**Issue by sergitejada** [aviflombaum/shadcn-rails#39]
I'm passing classes to a button and I don't see the classes merged, only added.
![image](https://github.com/aviflombaum/shadcn-rails/assets/49126831/32551291-cacd-4408-a3a0-a5525f0b8f4d)
![image](https://github.com/aviflombaum/shadcn-rails/assets/49126831/b1d3147c-750e-4245-9b48-9e1e6a88043f)
If i manualy add TW merge
![image](https://github.com/aviflombaum/shadcn-rails/assets/49126831/40175102-f6c2-47d2-a8e4-b10bc17b30b0)
![image](https://github.com/aviflombaum/shadcn-rails/assets/49126831/3e25dcf6-5fa2-42d6-9b62-59857a3f8ded)

**Comment by aviflombaum** [comment]
Closed by #40
