### ISSUE TITLE
Component sheet open by default

### ISSUE THREAD

**Issue by sergitejada** [aviflombaum/shadcn-rails#41]
By default the component is open
![image](https://github.com/aviflombaum/shadcn-rails/assets/49126831/cf292834-6a50-4e33-801c-97bd1fb0da80)
![image](https://github.com/aviflombaum/shadcn-rails/assets/49126831/c7f339bc-a0fc-4d64-9473-1466fc4f63d4)
if you add hidden by default, it works fine. (I don't think this is the best solution)
And other issus the component don't accept custom class in render_sheet i add this 
![image](https://github.com/aviflombaum/shadcn-rails/assets/49126831/37026a3d-75aa-4e62-af55-8aa8ef68cd8d)

**Comment by aviflombaum** [comment]
Pretty sure I fixed both of these. #35e1849
