### ISSUE TITLE
Hover Card Component Error

### ISSUE THREAD

**Issue by dchun** [aviflombaum/shadcn-rails#53]
I get the following error in the browser console after adding the Hover Card Component:

```javascript
stimulus-loading-3576ce92b149ad5d6959438c6f291e2426c86df3b874c525b30faad51b0d96b3.js:26 Failed to register controller: ui--hover-card (controllers/ui/hover-card_controller) TypeError: Failed to resolve module specifier "hotkeys-js". Relative references must start with either "/", "./", or "../".
```
I searched in the hover card controller file but can't find a reference to a hotkeys-js file

**Comment by dchun** [comment]
I seem to be getting the same error for the tooltip component as well

**Comment by aviflombaum** [comment]
Are you using importmaps? I haven't looked at this in a while but I know it really only supports importmaps. You might have to manually add hotkeys-js to your importmaps.

**Comment by dchun** [comment]
You are correct sir. Muchos gracias
