### ISSUE TITLE
Sheet misaligned from right on documentation

### ISSUE THREAD

**Issue by aviflombaum** [aviflombaum/shadcn-rails#7]
![CleanShot 2023-07-14 at 07 14 22](https://github.com/aviflombaum/shadcn-rails/assets/4515/d038cf39-d413-4a70-8bf3-e4810eb7373b)

Issue is on http://localhost:3000/docs/components/sheet

This is probably just a weird css bug.

**Comment by aviflombaum** [comment]
It doesn't look like it's happening on the left side with the mobile menu.
![CleanShot 2023-07-14 at 08 00 58](https://github.com/aviflombaum/shadcn-rails/assets/4515/21e5f9db-eb0a-4e11-8aec-54ec9fd8476f)

**Comment by condef5** [comment]
I'm gonna work on this :)

**Comment by aviflombaum** [comment]
Thank you!
